### PR TITLE
Quicklispability

### PR DESCRIPTION
**Pull request by gwangjinkim**
I reordered my github and put all my changes into a separate branch called 'quicklispability' - a feature branch.

So `master` branch is syncted to your branch - so we are in the same state there.

you switch between the branches by:

```
git checkout quicklispability
## => then your git repo folder will have my state - after you accepted the pull request and did this.

## and you can go anytime back to your current state by:
git checkout master
```

In this way, our changes won't disturbe or break things each other.
But we can any time cherrypick (transfer) single commits from your branch to my or the other way round.

So, since the changes are separated into branches, it is now easier for you.
You can accept all my changes without worrying that it would break your old state.

and at some point, when we think the quicklispablity branch is mature enough, we can merge all the changes with the master branch. - Or we could swap the branches I guess.
In this way all the states are preserved - and you can come back to the state now anytime you want. And go on in the current master branch with changing stuff. - That's beautiful with git.

Also in future, if we want to add new features, we will start a new branch by
```
git checkout -b mynewbranch

# the -b is for branch and creates a new branch.
# leave out the -b for switching around between the branches:

git checkout master             # => git folder will be in the state of master
git checkout mynewbranch # => switching back to new branch
```
and work there and merge only when everything is done well.

### CODE REVIEW

**Comment by gwangjinkim** [comment]
As you see this generates no conflicts with your base `master` branch.

So just accept - then our repositories are in sync.

**Comment by davypough** [comment]
A lot of what you wrote I don't understand, but I've invited you as collaborator. I thought we were creating a separate branch called quicklispable in my wouldwork repo, but after merging I don't see it. Instead it has overwritten my master, which I wanted to keep as my original code. Do I have to create the quicklispable branch myself and then sync it with yours? (If so, I'll need directions.) Can I get my master back, or do I need to upload it again?

Also, I have a notification: make wouldwork quicklisp-able #2 that seems to display an error message: We went looking everywhere, but couldn’t find those commits. Don't know if this is important or not.

**Comment by gwangjinkim** [comment]
Dear Dave,

oh I didn't want to create confusions. That's why I created the branch.

After merging, you should now see any changes. That is correct.
It is because you are in your master branch.

So go on your local computer to the folder from where you do gitpush
to get your changes to your github Wouldwork repository.

there in your local Wouldwork folder do first:
```
git pull
```
no matter what.
Then, you are in sync with your remote repository.

Now, what you do - to see my branch is:
```
git checkout quickloadability
```
Then the filestructure should change - and don't panick.
Everything from your remote folder (master) is still somewhere.

You can anytime recreate your master state by:
```
git checkout master
```
try it.

So only with the state of
```
git checkout quickloadability
```
You will be able to quickload.
But if you go back to your old state:
```
git checkout master
```
everything is back to normal.

The file content changes according to the branch. That is the magic of git.
It is like a "timemachine" or better: "statemachine".
Every git commit is like a snapshot.
And you can recreate anytime any commit's state by `git checkout <commit's
hash>`.

**Comment by gwangjinkim** [comment]
that #2 commit we can delete. Because this pullrequest already contained all changes from #2. I deleted the request to not confuse even more.

**Comment by gwangjinkim** [comment]
Ho no I see what happened. You mreged #2 to master.
I retracted the pull request - but I thought It would disappear from your repository, too, but it didn't.
So you have some changes played on your main repo.

We are in git - a state machine. So don't worry - one can recreate the state before.
try to do `git log`. And see what was the last commit from you. - ah let me do that form my fork.

**Comment by gwangjinkim** [comment]
By the way - you can explain Chagpt the situation - and ask it for
instructions how to recreate the former state - it will give you detailed
instrucitons.

And if you are unsure - copy your entire git repo locally first

and then follow chatgpt's instructions.

**Comment by davypough** [comment]
OK, not to worry. I couldn't do it the normal git way, but I was able to simply overwrite my wouldwork github repo with the files from my local wouldwork directory (by uploading and re-committing).

I'm a little uneasy with us both making changes and only integrating them later, based on my development experience. I would prefer that we maintain a good always running/tested master state preferably at your site that we incrementally update and test. I was originally thinking of sending my new (locally tested) updated files to your site for your evaluation and commitment to your master, while you would test and commit your changes directly to your master. I could then download your master and check for errors while testing my next changes before sending my changed files on to you. I'm not wedded to this approach, but I do think you are best placed, with your knowledge of git, to be the integrator. Let me know if you are specifically against such a back and forth incremental approach.

**Comment by gwangjinkim** [comment]
I think we should use git as it is intended.

As long as we are using git - we can't really break anything.
As long as we commit in small steps.
Every commit is a snapshot to which we can jump back - this is our safety
net.
Git is like a graph of states - every commit/snapshot is a node - every
node has an address (you can see the addresses - hashes if you fire: git log

```

commit 50586d5836653fb99c4c8159b2eb46c3de1898cb (*HEAD* -> *master*,
*origin/master*, *origin/HEAD*)

Author: Dave Brown ***@***.***>

Date:   Fri Sep 13 11:46:00 2024 -0700


    Delete README (for Gwang Jin).md


commit 2a3a8402177f447644adba9087f22c0dc9b67ca2

Author: Dave Brown ***@***.***>

Date:   Mon Sep 9 13:21:13 2024 -0700


    Add files via upload


commit 718f531792e8ea84f9f9dc6da4670c87769349c7

Author: Dave Brown ***@***.***>

Date:   Mon Sep 2 17:50:02 2024 -0700


    Add files via upload
```
so every commit has next to it a long hash - you need only the first 7
characters of the hash is enough.

So if you do
```
git checkout 718f531
```
your folder (and files) will be in the state where you did the pre-previous
commit.
you can add there changes and commit new - that would create a new commit
point - which is branching out from your last checkout's node.
You can add changes - commit - add changes - commit
So if we make mistakes and he thing doesn't run - we just git checkout to
the previous point.

With
```
git checkout 50586d58
```
you can jump back anytime to the current state back.

The beautiful thing is this graph can grow in any direction from any of the
nodes.
Yet you can anytime jump to another branch or to a previous point.
And when you do that git checkout - you will see all your files in the
repository changed their content to the snapshot's state.

It is not so difficult - we can do it - and especially at the beginning,
googling and chatgpt-ing will help us when more complicated changes have to
be made with git.

**Comment by gwangjinkim** [comment]
I see now however - you already merged - that's not how it should have been
done.

**Comment by gwangjinkim** [comment]
The idea was to keep the branches separate. oh no ...

**Comment by gwangjinkim** [comment]
Ah you didn't merge but your forced back to previous state - I thought
everything was merged.

**Comment by gwangjinkim** [comment]
ok - then we do changes on my github repository.

But then you have to clone onto your machine my repository and if you do
changes, you push to my repository?
important: Always before you add something - do first a `git pull` - that
should be always a habit.

I think it won't be difficult to work with git - and the advantages are
much bigger than sending files around - the confusion there will be greater.

As long you make often enough commits - you can always jump back to
recreate a previous state.
We really should use git.

**Comment by gwangjinkim** [comment]
actually bigger changes should be always done into branches. THAT ensures
that there is always one working solution (the master)
which works.
Changes are done in branches and then if everything is enough tested, only
then we merge the branch onto the master - so that the users will always
have a working version in the master branch.

**Comment by gwangjinkim** [comment]
Maybe we should do a call via zoom or such. Do you have telegram? or
whatsapp?

**Comment by davypough** [comment]
No, but using git is fine. I just want you to do all the commits. I can access your updated repo as needed to continue my updating here. I'd like to do file pushes to your repo, but you should look them over first before committing. I will have tested the updates, but after you commit them, you should test the new master with all our test problems. I just need to figure out how to push a file to your repo using the gui (and not the command line at this point).

**Pull request merged**
